name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests and save output
        id: test
        run: |
          node test.js 2>&1 | tee test.log
          test ${PIPESTATUS[0]} -eq 0

      - name: Send logs to n8n if failed
        if: failure()
        run: |
          LOGS=$(tail -n 100 test.log | jq -Rs .)
          curl -X POST https://ihebkraiem.app.n8n.cloud/webhook-test/ci-failure \
            -H "Content-Type: application/json" \
            -d "{\"logs\": $LOGS}"
                  - name: Send success to n8n
      - name: Send success to n8n
        if: success()
        run: |
          LOGS=$(tail -n 100 test.log | jq -Rs .)
          curl -X POST https://ihebkraiem.app.n8n.cloud/webhook-test/ci-failure \
            -H "Content-Type: application/json" \
            -d "{\"status\": \"success\", \"logs\": $LOGS}"





