name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Run tests
        id: test
        run: |
          # Simule un test qui peut échouer
          npm install
          npm test

      - name: Send logs to n8n if failed
        if: failure()
        run: |
          echo "Sending logs to n8n..."
          LOGS=$(tail -n 100 ./test.log || echo "No test log")
          curl -X POST https://ihebkraiem.app.n8n.cloud/webhook-test/ci-failure \
            -H "Content-Type: application/json" \
            -d "{\"logs\": \"$LOGS\"}"